import {pageMetadata} from '@/lib/metadata';
import {institutionalImages} from '@/lib/editorial-images';
import {InstitutionalHero,EditorialPhoto} from '@/components/Institutional';
import type {Metadata} from 'next';
import Link from 'next/link';
import {Check,Plus} from 'lucide-react';
import {services,serviceHref} from '@/lib/content';
import {CTA} from '@/components/Shell';
export const metadata:Metadata=pageMetadata("Soluções de geotecnia e fundações","Conheça os cinco serviços da For Infra: sondagem SPT, projetos de fundações, estacas escavadas, Strauss e consultoria técnica.","/solucoes/");
export default function Solutions(){return <main tabIndex={-1} id="conteudo" className="institutional-page solutions-editorial"><InstitutionalHero title={'Uma engenharia.\nCinco frentes.'} text="Do conhecimento do solo ao trabalho em campo. Encontre o serviço para a etapa da sua obra ou converse sobre um escopo integrado." href="#servicos" label="Explorar soluções"/><EditorialPhoto {...institutionalImages.solutions}/><nav id="servicos" className="service-nav" aria-label="Serviços">{services.map(s=><a key={s.id} href={`#${s.id}`}>{s.number} / {s.title}</a>)}</nav>{services.map(s=><section id={s.id} key={s.id} className="solution-section"><span className="solution-number" aria-hidden="true">{s.number}</span><div className="solution-text"><span className="eyebrow">{s.category}</span><h2>{s.title}</h2><p>{s.description}</p><div className="service-stage"><strong>Quando conversar com a gente</strong><br/>{s.stage}</div></div><div className="deliverables"><h3>O QUE PODE COMPOR O ESCOPO</h3><ul>{s.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><Link href={serviceHref(s.id)} className="text-link">Conheça o serviço <Plus size={15}/></Link></div></section>)}<section className="section"><div className="faq"><span className="eyebrow dark">ANTES DE COMEÇAR</span><h2>As primeiras dúvidas,<br/><em>respondidas.</em></h2><details><summary>Posso contratar apenas um dos serviços?</summary><p>Sim. O contato inicial serve para entender a etapa da obra e definir o escopo necessário, seja uma sondagem, um projeto, a execução ou uma consultoria.</p></details><details><summary>Como saber qual tipo de fundação utilizar?</summary><p>A definição depende dos dados do terreno, das cargas, das condições do entorno e da análise de projeto. Compartilhe as informações disponíveis para que a equipe avalie os próximos passos.</p></details><details><summary>Quais informações ajudam no orçamento?</summary><p>Cidade da obra, tipo de empreendimento, etapa atual e previsão de início. Se disponíveis, o relatório de sondagem, a planta de cargas e os projetos ajudam a detalhar a avaliação.</p></details><details><summary>O formulário gera um preço automático?</summary><p>Não. Ele organiza as informações iniciais e prepara uma mensagem para o WhatsApp. A proposta depende da análise do escopo e das condições da obra pela equipe.</p></details></div></section><CTA/></main>}
