import type {Metadata} from 'next';
import Link from 'next/link';
import {CTA,ActionMark} from '@/components/Shell';
import {EditorialPhoto} from '@/components/Institutional';
export const metadata:Metadata={title:'Nossa história e a For Infra',description:'Conheça a For Infra Engenharia: experiência de campo, atuação familiar e uma visão integrada da investigação do solo ao projeto e à execução de fundações.'};
const chapters=[
 {title:'Experiência que orienta decisões.',label:'Conhecimento de campo',text:'A experiência da nossa equipe em geotecnia e fundações está na base da For Infra. Conhecer o terreno, compreender as exigências da estrutura e considerar as condições de execução fazem parte do nosso trabalho.'},
 {title:'Uma visão completa da fundação.',label:'Engenharia integrada',text:'Da investigação do solo ao projeto e à execução, conectamos informações para orientar cada etapa. As decisões consideram o empreendimento como um todo e as particularidades de cada canteiro.'},
 {title:'Proximidade em cada etapa.',label:'Relação com o cliente',text:'Como empresa familiar, valorizamos a comunicação direta e escopos bem definidos. A experiência compartilhada pela equipe se traduz em atenção às necessidades de quem projeta, contrata e executa.'}
];
export default function About(){return <main tabIndex={-1} id="conteudo" className="institutional-page about-editorial">
 <section className="about-opening"><div className="about-opening-copy"><nav aria-label="Nesta página" className="about-section-nav"><a href="#historia">Nossa história</a><a href="#familia">Quem somos</a><a href="#metodo">Nosso método</a></nav><h1>Engenharia de base.<br/><em>Experiência em campo.</em></h1><p>Conhecimento do solo, critério técnico<br/>e experiência prática para planejar<br/>e executar as fundações da sua obra.</p><Link href="#historia" className="button">Conheça nossa história<ActionMark/></Link></div><EditorialPhoto src="/assets/canteiro.webp" alt="Imagem conceitual de um canteiro de fundações ao amanhecer"/></section>
 <section id="historia" className="about-history"><div className="about-history-title reveal"><span className="history-brand-line">FOR INFRA ENGENHARIA</span><h2>Conhecimento<br/>construído<br/><em>em campo.</em></h2><p>A experiência de quem conhece o terreno faz parte de cada decisão de engenharia.</p></div><div className="history-chapters">{chapters.map(c=><article key={c.label} className="reveal"><span className="history-chapter-label">{c.label}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
 <section id="familia" className="about-family"><div className="family-statement reveal"><span>O que nos aproxima</span><h2>Família.<br/>Trabalho.<br/><em>Compromisso.</em></h2></div><div className="family-copy reveal"><h3>Uma empresa feita<br/>por pessoas próximas.</h3><p>Somos uma equipe familiar, com a participação de marido, esposa, pai e tia. Pessoas que compartilham o trabalho e a dedicação à engenharia.</p><p>Essa proximidade está na origem da For Infra. A experiência compartilhada e a participação de cada um dão forma à maneira como seguimos trabalhando juntos.</p><p className="family-copy-end">Experiência compartilhada.<br/>Compromisso com cada obra.</p></div></section>
 <section className="institutional-split about-vision"><h2>Do conhecimento<br/>do solo à realidade<br/>do canteiro.</h2><div><p className="institutional-lead">O terreno, a estrutura e a execução fazem parte da mesma conversa.</p><p>Atuamos em sondagem SPT, projetos de fundações, estacas escavadas, estacas Strauss e consultoria pré e pós-obra. Os serviços podem ser discutidos separadamente ou em um escopo integrado.</p><Link className="button" href="/solucoes/">Explore nossas soluções<ActionMark/></Link></div></section>
 <section id="metodo" className="institutional-method"><div className="reveal"><h2>Clareza para decidir.<br/>Critério para executar.</h2><p>Uma sequência de trabalho que conecta as necessidades da obra às decisões de engenharia.</p></div><ol>{[['Entender o cenário','Conhecer a etapa da obra, os documentos disponíveis e a necessidade do contratante.'],['Definir o escopo','Alinhar serviços, entregas e responsabilidades, identificando as informações que ainda precisam ser reunidas.'],['Conectar as disciplinas','Relacionar as condições do terreno, as exigências da estrutura e as possibilidades de execução.'],['Registrar e comunicar','Documentar o trabalho e comunicar as condições encontradas, conforme o escopo contratado.']].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
 <section className="institutional-field"><EditorialPhoto src="/assets/projeto.webp" alt="Imagem conceitual de análise de projeto no canteiro"/><div className="reveal"><h2>O projeto encontra<br/>o trabalho em campo.</h2><p>Acessos, interferências, mobilização e condições encontradas no terreno fazem parte do planejamento. Aproximar essas informações do projeto orienta a organização do trabalho.</p><Link className="button" href="/obras/">Conheça as aplicações<ActionMark/></Link></div></section><CTA/></main>}
