'use client';
import {assetUrl} from '@/lib/paths';
import {photoSources} from '@/lib/images';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import Script from 'next/script';
import {services,serviceHref} from '@/lib/content';
import {ActionMark} from '@/components/Shell';
const frames=[{src:'/assets/canteiro.webp',label:'Execução de fundações',position:'center 58%'},{src:'/assets/solo.webp',label:'Investigação do solo',position:'center'},{src:'/assets/projeto.webp',label:'Projeto & consultoria',position:'center'}];
const servicePhotos=[frames[1],frames[2],frames[0],{...frames[2],position:'right center'}, {...frames[2],position:'left center'}];
export function EditorialHero(){const[active,setActive]=useState(0);const[visited,setVisited]=useState([0]);return <section className="editorial-hero" aria-label="For Infra Engenharia"><div className="hero-frames">{frames.map((f,i)=>visited.includes(i)&&<img key={f.src} src={assetUrl(f.src)} alt="" aria-hidden="true" className={active===i?'hero-frame active':'hero-frame'} style={{objectPosition:f.position}} fetchPriority={i===0?'high':'auto'}/>)}</div><div className="editorial-hero-shade"/><div className="hero-editorial-copy"><h1>Solidez<br/>desde a base<span>.</span></h1><p>Investigação do solo, projetos e execução.<br/>Engenharia que conecta cada etapa da sua obra.</p></div><div className="hero-selector" aria-label="Fotografias da abertura">{frames.map((f,i)=><button key={f.label} aria-pressed={active===i} onClick={()=>{setVisited(v=>v.includes(i)?v:[...v,i]);setActive(i)}}><span>{f.label}</span><i aria-hidden="true"/></button>)}</div><div className="hero-editorial-actions"><Link href="/solucoes/" className="button">Nossas soluções <ActionMark/></Link><Link href="/contato/" className="button secondary">Vamos conversar <ActionMark/></Link></div><span className="concept-caption">Imagens conceituais</span><div className="dot-field" aria-hidden="true"/></section>}
export function EditorialServices(){const[active,setActive]=useState(0);const wrap=useRef<HTMLDivElement>(null);
useEffect(()=>{const sections=Array.from(wrap.current?.querySelectorAll<HTMLElement>('.service-chapter')||[]);const update=()=>{const aim=window.innerHeight*.48;let closest=0,dist=Infinity;sections.forEach((s,i)=>{const r=s.getBoundingClientRect();const d=Math.abs((r.top+r.bottom)/2-aim);if(d<dist){dist=d;closest=i}});setActive(closest)};let frame=0;const scroll=()=>{if(!frame)frame=requestAnimationFrame(()=>{update();frame=0})};update();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);cancelAnimationFrame(frame)}},[]);
return <section id="servicos" className="editorial-services" ref={wrap}><div className="service-photo-sticky"><div className="service-photo-stack">{servicePhotos.map((f,i)=><img key={i} src={assetUrl(f.src)} srcSet={photoSources(f.src)} sizes="(min-width: 900px) 53vw, 88vw" alt="" loading="lazy" className={active===i?'active':''} style={{objectPosition:f.position}}/>)}<div className="photo-shade"/><div className="service-counter" aria-live="off">0{active+1} <span>/ 05</span></div><nav className="chapter-dots" aria-label="Ir para serviço">{services.map((s,i)=><a key={s.id} href={`#chapter-${s.id}`} className={i===active?'active':''} aria-label={s.title} aria-current={i===active?'step':undefined}><i/></a>)}</nav><span className="photo-caption">Imagem conceitual</span><Link href="/solucoes/" className="button secondary">Todas as soluções <ActionMark/></Link></div></div><div className="service-chapters">{services.map((s,i)=><article id={`chapter-${s.id}`} className="service-chapter" key={s.id}><div className="mobile-service-photo"><img src={servicePhotos[i].src} srcSet={photoSources(servicePhotos[i].src)} sizes="88vw" alt={`Imagem conceitual para ${s.title.toLowerCase()}`} loading="lazy" style={{objectPosition:servicePhotos[i].position}}/><span>Imagem conceitual</span></div><div className="chapter-copy"><span className="section-kicker">Nossas soluções <span>{s.number} / 05</span></span><h2>{s.title}</h2><p>{s.description}</p><p className="chapter-detail">{s.intro}</p><Link href={serviceHref(s.id)} className="button">Conheça o serviço <ActionMark/></Link></div></article>)}</div></section>}
type AnimationEngine={registerPlugin:(p:unknown)=>void;matchMedia:()=>{add:(q:string,f:()=>void)=>void;revert:()=>void};fromTo:(target:unknown,from:unknown,to:unknown)=>void};
export function EditorialMotion(){const[engine,setEngine]=useState(false);const[ready,setReady]=useState(false);const[enabled,setEnabled]=useState(false);
useEffect(()=>{const media=window.matchMedia('(min-width: 900px) and (prefers-reduced-motion: no-preference)');const update=()=>setEnabled(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
useEffect(()=>{if(!ready)return;const runtime=window as unknown as {gsap:AnimationEngine;ScrollTrigger:{refresh:()=>void}};const{gsap,ScrollTrigger}=runtime;if(!gsap||!ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{gsap.fromTo('.hero-editorial-copy',{y:0,opacity:1},{y:75,opacity:.2,ease:'none',scrollTrigger:{trigger:'.editorial-hero',start:'top top',end:'bottom 20%',scrub:1}});gsap.fromTo('.editorial-field-image img',{yPercent:-5},{yPercent:5,ease:'none',scrollTrigger:{trigger:'.editorial-field-image',start:'top bottom',end:'bottom top',scrub:1}})});document.fonts.ready.then(()=>ScrollTrigger.refresh());return()=>mm.revert()},[ready]);
if(!enabled)return null;
return <><Script src={assetUrl("/gsap.min.js")} strategy="afterInteractive" onReady={()=>setEngine(true)}/>{engine&&<Script src={assetUrl("/ScrollTrigger.min.js")} strategy="afterInteractive" onReady={()=>setReady(true)}/>}</>}
