import {serviceImages} from '@/lib/editorial-images';
import {photoSources} from '@/lib/images';
import Link from 'next/link';
import {Check,ChevronRight} from 'lucide-react';
import {ActionMark} from '@/components/Shell';
import {serviceHref} from '@/lib/content';
import {servicePages} from '@/lib/service-pages';
export default function ServiceDetail({service}:{service:keyof typeof servicePages}){
 const d=servicePages[service];const preparation=serviceImages[service].prepare;const quote=`/contato/?servico=${d.id}`;
 return <main tabIndex={-1} id="conteudo" className={`service-detail-page detail-${service}`}>
  <section className="detail-heading"><nav className="detail-breadcrumb" aria-label="Caminho da página"><Link href="/">Início</Link><ChevronRight size={12}/><Link href="/solucoes/">Soluções</Link><ChevronRight size={12}/><span aria-current="page">{d.title}</span></nav><div className="detail-title-row"><h1>{d.firstLine}<br/>{d.secondLine}</h1><div><span className="section-kicker">{d.kicker}</span><p>{d.heroText}</p><Link href={quote} className="button">Vamos conversar <ActionMark/></Link></div></div><div className="dot-field" aria-hidden="true"/></section>
  <figure className="detail-cover"><img src={d.image} srcSet={photoSources(d.image)} sizes="100vw" alt={d.imageAlt} style={{objectPosition:d.imagePosition}} fetchPriority="high"/><figcaption>Imagem conceitual</figcaption><a className="detail-cover-link" href="#visao-geral">Conheça o serviço <span aria-hidden="true">↓</span></a></figure>
  <section id="visao-geral" className="detail-overview"><div className="reveal"><span className="section-kicker">{service==='consultoria'?'Um olhar sobre o todo':service==='sondagem'?'Investigação geotécnica':(service==='escavadas'||service==='strauss')?'Execução de fundações':'Engenharia de projeto'}</span><h2>{d.introTitle}</h2></div><div className="detail-overview-copy reveal"><p className="detail-lead">{d.introLead}</p><p>{d.introText}</p><p>{d.introExtra}</p></div></section>
  <section className="detail-context"><div className="detail-context-title reveal"><span className="section-kicker">{service==='consultoria'?'Quando contar com a For Infra':'O ponto de partida'}</span><h2>{d.contextsTitle}</h2></div><div className="detail-context-list">{d.contexts.map((c,i)=><article key={c.title} className="reveal"><span>0{i+1}</span><div><h3>{c.title}</h3><p>{c.text}</p></div></article>)}</div></section>
  <section className="detail-scope"><div className="detail-scope-intro reveal"><span className="section-kicker">O que pode compor o escopo</span><h2>{d.scopeTitle}</h2><p>{d.scopeText}</p></div><div className="detail-scope-list">{d.scope.map(([title,text],i)=><div className="detail-scope-item" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
  <section className="detail-process"><div className="detail-process-title reveal"><span className="section-kicker">Como trabalhamos</span><h2>{d.processTitle}</h2></div><ol>{d.process.map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
  <section className="detail-prepare"><div className="detail-prepare-photo"><img src={preparation.src} srcSet={photoSources(preparation.src)} sizes="(min-width: 900px) 50vw, 88vw" alt={preparation.alt} style={{objectPosition:preparation.position}} loading="lazy"/><span>Imagem conceitual</span></div><div className="detail-prepare-copy"><span className="section-kicker">Prepare a primeira conversa</span><h2>{d.checklistTitle}</h2><ul>{d.checklist.map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul><p>{d.checklistNote}</p><Link href={quote} className="button">Contar sobre minha obra <ActionMark/></Link></div></section>
  <section className="detail-faq"><div><span className="section-kicker">Antes de começar</span><h2>Perguntas<br/>frequentes.</h2></div><div className="faq">{d.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section className="detail-related"><span className="section-kicker">A engenharia continua</span><Link href={serviceHref(d.relatedId)}><div><h2>{d.relatedTitle}</h2><p>{d.relatedText}</p></div><ActionMark/></Link></section>
  <section className="cta editorial-cta detail-cta"><div><span className="section-kicker">Fale com a For Infra</span><h2>{d.ctaTitle}</h2></div><div className="cta-side"><p>{d.ctaText}</p><Link className="button light" href={quote}>{d.ctaLabel} <ActionMark/></Link></div></section>
 </main>
}
