'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {Menu,X,Plus,ChevronDown} from 'lucide-react';
import {directContact,services,serviceHref} from '@/lib/content';
export function Logo(){return <span className="logo"><span className="logo-mark" aria-hidden="true"><i/><i/><i/></span><span>For Infra<span className="logo-dot">.</span><small>ENGENHARIA</small></span></span>}
export function ActionMark(){return <span className="action-mark" aria-hidden="true"><Plus size={15}/></span>}
export function Header(){const path=usePathname();const[open,setOpen]=useState(false);const[mega,setMega]=useState(false);const[scrolled,setScrolled]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const servicesToggle=useRef<HTMLButtonElement>(null);
useEffect(()=>{setOpen(false);setMega(false)},[path]);
useEffect(()=>{const scroll=()=>setScrolled(window.scrollY>40);scroll();window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll)},[]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(mega){setMega(false);servicesToggle.current?.focus()}else if(open){setOpen(false);toggle.current?.focus()}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mega,open]);
return <><a href="#conteudo" className="skip">Pular para o conteúdo</a><header className={`header editorial-header ${path==='/'&&!scrolled&&!open&&!mega?'over-photo':'solid'}`}><Link href="/" title="Página inicial da For Infra"><Logo/></Link><button ref={toggle} className="menu-toggle" aria-expanded={open} aria-controls="navigation" onClick={()=>{setOpen(!open);setMega(false)}} aria-label={open?'Fechar menu':'Abrir menu'}>{open?<X/>:<Menu/>}</button><nav id="navigation" className={open?'nav open':'nav'} aria-label="Principal"><Link href="/sobre/" aria-current={path.startsWith('/sobre')?'page':undefined}>A For Infra</Link><div className="nav-solutions-group"><button ref={servicesToggle} className="nav-services" aria-expanded={mega} aria-controls={mega?"services-menu":undefined} onClick={()=>setMega(!mega)}>Soluções <ChevronDown size={13}/></button>{mega&&<div id="services-menu" className="mega-menu"><div><span className="section-kicker">Nossa engenharia</span><h2>Da investigação<br/>à execução.</h2><Link href="/solucoes/" className="text-link" onClick={()=>setMega(false)}>Todas as soluções <Plus size={16}/></Link></div><div>{services.map(s=><Link key={s.id} href={serviceHref(s.id)} onClick={()=>{setMega(false);setOpen(false)}}><span>{s.number}</span>{s.title}<Plus size={16}/></Link>)}</div></div>}</div><Link href="/obras/" aria-current={path.startsWith('/obras')?'page':undefined}>Obras & aplicações</Link><Link href="/sobre/#metodo" onClick={()=>{setOpen(false);setMega(false)}}>Nosso método</Link><Link href="/contato/" className="button small">Contato <ActionMark/></Link></nav></header><noscript><nav className="no-script-nav" aria-label="Navegação sem JavaScript"><Link href="/sobre/">A For Infra</Link><Link href="/solucoes/">Soluções</Link><Link href="/obras/">Obras & aplicações</Link><Link href="/contato/">Contato</Link></nav></noscript>{mega&&<button className="menu-backdrop" tabIndex={-1} aria-label="Fechar menu de soluções" onClick={()=>setMega(false)}/>}</>}
export function Footer(){return <footer className="editorial-footer"><div className="footer-columns"><div className="footer-brand"><Link href="/" title="Página inicial da For Infra"><Logo/></Link><p>O conhecimento do solo.<br/>A força da engenharia.</p></div><div><h3>A For Infra</h3><Link href="/sobre/#historia">Nossa história</Link><Link href="/sobre/#familia">Quem somos</Link><Link href="/sobre/#metodo">Nosso método</Link><Link href="/obras/">Obras & aplicações</Link></div><div><h3>Soluções</h3>{services.map(s=><Link key={s.id} href={serviceHref(s.id)}>{s.title}</Link>)}</div><div><h3>Vamos conversar</h3><a href={directContact} target="_blank" rel="noopener noreferrer">(37) 99937-6345</a><Link href="/contato/">Conte sobre sua obra</Link><p className="footer-note">Geotecnia, projetos<br/>e execução de fundações.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} For Infra Engenharia.</span><span>Solidez desde a base.</span><Link href="/contato/#privacidade">Privacidade</Link></div></footer>}
export function CTA(){return <section className="cta editorial-cta"><div><span className="section-kicker">Vamos trabalhar juntos</span><h2>Uma boa conversa.<br/>Uma base sólida.</h2></div><div className="cta-side"><p>Conte em que etapa sua obra está.<br/>Vamos entender o que ela precisa.</p><Link className="button light" href="/contato/">Fale com a For Infra <ActionMark/></Link></div></section>}
export function Reveals(){const path=usePathname();useEffect(()=>{const nodes=document.querySelectorAll('.reveal');if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');obs.unobserve(entry.target)}}),{threshold:.08});nodes.forEach(n=>obs.observe(n));return()=>obs.disconnect()},[path]);return null}
export function PlusMark(){return <Plus size={20} aria-hidden="true"/>}
